version: '2.1'
services:
  terraform:
    image: "quay.io/azavea/terraform:0.9.11"
    volumes:
      - ./:/usr/local/src
    environment:
      - PC_DEMO_DEBUG=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ECR_ENDPOINT=${AWS_ECR_ENDPOINT}
      - TRAVIS_COMMIT=${TRAVIS_COMMIT}
      - PC_DEMO_SETTINGS_BUCKET=${PC_DEMO_SETTINGS_BUCKET:-geotrellis-site-production-config-us-east-1}
    working_dir: /usr/local/src
    entrypoint: bash
