version: '2.1'
services:
  terraform:
    image: "quay.io/azavea/terraform:0.9.11"
    volumes:
      - ~/.aws:/root/.aws
    environment:
      - GT_TRANSIT_DEBUG=1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_PROFILE=${AWS_PROFILE:-geotrellis}
