---
- hosts: all
  become: True

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - { role: "azavea.ntp" }
    - { role: "azavea.terraform" }
    - { role: "azavea.python-security" }
    - { role: "pc-demo.aws-cli" }
    - { role: "pc-demo.docker" }
    - { role: "pc-demo.shellcheck" }
